// Code generated by detectors-gen. DO NOT EDIT.

package all

import (
	"github.com/Roro1727/airom/pkg/airom/detect"
)

// Builtin returns every built-in detector, sorted by import path then
// constructor. The composition root adds them to the catalog explicitly
// (no init() registration, decision D4).
func Builtin() []detect.Detector {
	return []detect.Detector{}
}
