// Code generated by detectors-gen. DO NOT EDIT.

package all

import (
	"github.com/airomhq/airom/pkg/airom/detect"

	"github.com/airomhq/airom/internal/detectors/dataset"

	"github.com/airomhq/airom/internal/detectors/gosrc"

	"github.com/airomhq/airom/internal/detectors/infra"

	"github.com/airomhq/airom/internal/detectors/manifest"

	"github.com/airomhq/airom/internal/detectors/modelfile"

	"github.com/airomhq/airom/internal/detectors/modelfilex"

	"github.com/airomhq/airom/internal/detectors/project"

	"github.com/airomhq/airom/internal/detectors/prompt"
)

// Builtin returns every built-in detector, sorted by import path then
// constructor. The composition root adds them to the catalog explicitly
// (no init() registration, decision D4).
func Builtin() []detect.Detector {
	return []detect.Detector{
		dataset.NewDataset(),
		gosrc.NewGoSource(),
		infra.NewCompose(),
		infra.NewDockerfile(),
		manifest.NewCSProj(),
		manifest.NewCargo(),
		manifest.NewGoMod(),
		manifest.NewGradle(),
		manifest.NewInstalled(),
		manifest.NewMaven(),
		manifest.NewPackageJSON(),
		manifest.NewPackageLock(),
		manifest.NewPipfileLock(),
		manifest.NewPnpmLock(),
		manifest.NewPoetryLock(),
		manifest.NewPyProject(),
		manifest.NewRequirements(),
		manifest.NewYarnLock(),
		modelfile.NewGGUF(),
		modelfile.NewONNX(),
		modelfile.NewSafetensors(),
		modelfilex.NewHDF5(),
		modelfilex.NewSavedModel(),
		modelfilex.NewTFLite(),
		modelfilex.NewTensorRT(),
		modelfilex.NewTorch(),
		project.NewAdapterLink(),
		project.NewConfigBind(),
		project.NewHFDir(),
		project.NewRAGLink(),
		prompt.NewPrompt(),
	}
}
