package pdf

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"sync"
	"time"
)

// Generator compiles DocumentSpec structures into valid ISO 32000-1 (PDF 1.7) documents.
type Generator struct {
	mu sync.RWMutex
}

// NewGenerator constructs a new executive PDF generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// GeneratePDF renders a publication-grade PDF document containing compliance summary and sections.
func (g *Generator) GeneratePDF(spec DocumentSpec) *PDFResult {
	g.mu.RLock()
	defer g.mu.RUnlock()

	now := time.Now().UTC()
	var buf bytes.Buffer
	var offsets []int

	// 1. PDF Header
	buf.WriteString("%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")

	// Object 1: Catalog
	offsets = append(offsets, buf.Len())
	buf.WriteString("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

	// Object 2: Pages Root
	offsets = append(offsets, buf.Len())
	buf.WriteString("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")

	// Object 4: Font Resource
	offsets = append(offsets, buf.Len())
	buf.WriteString("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

	// Build Page Content Stream (Object 5)
	var content bytes.Buffer
	content.WriteString("BT\n/F1 18 Tf\n50 750 Td\n(")
	content.WriteString(escapePDFText(spec.Title))
	content.WriteString(") Tj\n")

	content.WriteString("/F1 10 Tf\n0 -25 Td\n(Organization: ")
	content.WriteString(escapePDFText(spec.OrganizationName))
	content.WriteString(" | Repository: ")
	content.WriteString(escapePDFText(spec.RepositoryName))
	content.WriteString(" | Framework: ")
	content.WriteString(escapePDFText(spec.FrameworkName))
	content.WriteString(") Tj\n")

	content.WriteString("/F1 12 Tf\n0 -35 Td\n(Executive Summary:) Tj\n")
	content.WriteString("/F1 10 Tf\n0 -18 Td\n(")
	content.WriteString(escapePDFText(spec.ExecutiveSummary))
	content.WriteString(") Tj\n")

	content.WriteString("/F1 12 Tf\n0 -35 Td\n(Audit Telemetry:) Tj\n")
	content.WriteString("/F1 10 Tf\n0 -18 Td\n(Total Discovered AI Components: ")
	content.WriteString(fmt.Sprintf("%d | Controls Met: %d | Compliance Gaps: %d", spec.TotalComponents, spec.ControlsMet, spec.GapsIdentified))
	content.WriteString(") Tj\n")

	yOffset := -35
	for _, sec := range spec.Sections {
		content.WriteString(fmt.Sprintf("/F1 12 Tf\n0 %d Td\n(", yOffset))
		content.WriteString(escapePDFText(sec.Heading))
		content.WriteString(") Tj\n/F1 9 Tf\n0 -16 Td\n(")
		content.WriteString(escapePDFText(sec.Content))
		content.WriteString(") Tj\n")
		yOffset = -30
	}

	content.WriteString("/F1 8 Tf\n0 -40 Td\n(DISCLAIMER: Technical evidence mapping generated by AIROM Enterprise Platform. Not formal legal advice.) Tj\n")
	content.WriteString("ET\n")

	// Object 5: Content Stream
	offsets = append(offsets, buf.Len())
	fmt.Fprintf(&buf, "5 0 obj\n<< /Length %d >>\nstream\n", content.Len())
	buf.Write(content.Bytes())
	buf.WriteString("\nendstream\nendobj\n")

	// Object 3: Page Object
	offsets = append(offsets, buf.Len())
	buf.WriteString("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 5 0 R /Resources << /Font << /F1 4 0 R >> >> >>\nendobj\n")

	// Cross-Reference Table
	xrefOffset := buf.Len()
	fmt.Fprintf(&buf, "xref\n0 %d\n0000000000 65535 f \n", len(offsets)+1)
	for _, off := range offsets {
		fmt.Fprintf(&buf, "%010d 00000 n \n", off)
	}

	// Trailer
	fmt.Fprintf(&buf, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(offsets)+1, xrefOffset)

	raw := buf.Bytes()
	h := sha256.Sum256(raw)
	docID := fmt.Sprintf("pdf-%s", hex.EncodeToString(h[:6]))

	return &PDFResult{
		DocumentID: docID,
		SizeBytes:  len(raw),
		PageCount:  1,
		PDFBytes:   raw,
		CreatedAt:  now,
	}
}

func escapePDFText(raw string) string {
	raw = strings.ReplaceAll(raw, "\\", "\\\\")
	raw = strings.ReplaceAll(raw, "(", "\\(")
	raw = strings.ReplaceAll(raw, ")", "\\)")
	raw = strings.ReplaceAll(raw, "\n", " ")
	if len(raw) > 120 {
		raw = raw[:120] + "..."
	}
	return raw
}
