apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airom-enterprise.fullname" . }}-config
  labels:
    {{- include "airom-enterprise.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airom-enterprise.fullname" . }}-secrets
  labels:
    {{- include "airom-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIROM_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.stripeWebhookSecret }}
  AIROM_STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | quote }}
  {{- end }}
