apiVersion: v1
kind: Service
metadata:
  name: {{ include "airom-enterprise.fullname" . }}
  labels:
    {{- include "airom-enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      name: gateway
  selector:
    {{- include "airom-enterprise.selectorLabels" . | nindent 4 }}
