// Command detectors-gen regenerates internal/detectors/all/all.go: the
// mechanical, conflict-free registration list of built-in detectors
// (ARCHITECTURE.md §6.2, plugin-guide.md B.5). It scans
// internal/detectors/* for exported zero-argument constructors whose return
// type implements detect.Detector and emits them sorted by import path,
// then constructor name.
//
// Run via: go generate ./internal/detectors/all
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	modulePath  = "github.com/Roro1727/airom"
	detectPath  = modulePath + "/pkg/airom/detect"
	scanPattern = modulePath + "/internal/detectors/..."
	selfPkg     = modulePath + "/internal/detectors/all"
)

type entry struct {
	pkgPath string
	pkgName string
	fn      string
}

func main() {
	root, err := repoRoot()
	if err != nil {
		log.Fatal(err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedDeps,
		Dir:  root,
	}
	pkgs, err := packages.Load(cfg, scanPattern, detectPath)
	if err != nil {
		log.Fatal(err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		log.Fatal("detectors-gen: packages loaded with errors")
	}

	detectorIface := findDetectorInterface(pkgs)
	if detectorIface == nil {
		log.Fatalf("detectors-gen: cannot find %s.Detector", detectPath)
	}

	var entries []entry
	for _, p := range pkgs {
		if p.PkgPath == selfPkg || p.PkgPath == detectPath || !strings.HasPrefix(p.PkgPath, modulePath+"/internal/detectors/") {
			continue
		}
		scope := p.Types.Scope()
		for _, name := range scope.Names() {
			fn, ok := scope.Lookup(name).(*types.Func)
			if !ok || !fn.Exported() {
				continue
			}
			sig := fn.Type().(*types.Signature)
			if sig.Params().Len() != 0 || sig.Results().Len() != 1 || sig.Recv() != nil {
				continue
			}
			ret := sig.Results().At(0).Type()
			if types.Implements(ret, detectorIface) || types.Implements(types.NewPointer(ret), detectorIface) {
				entries = append(entries, entry{pkgPath: p.PkgPath, pkgName: p.Types.Name(), fn: name})
			}
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].pkgPath != entries[j].pkgPath {
			return entries[i].pkgPath < entries[j].pkgPath
		}
		return entries[i].fn < entries[j].fn
	})

	src, err := render(entries)
	if err != nil {
		log.Fatal(err)
	}
	out := filepath.Join(root, "internal", "detectors", "all", "all.go")
	if err := os.WriteFile(out, src, 0o644); err != nil { // #nosec G306 -- generated source file, checked into the repo
		log.Fatal(err)
	}
	fmt.Printf("detectors-gen: wrote %s (%d detector constructors)\n", out, len(entries))
}

func findDetectorInterface(pkgs []*packages.Package) *types.Interface {
	var iface *types.Interface
	packages.Visit(pkgs, nil, func(p *packages.Package) {
		if p.PkgPath != detectPath || iface != nil {
			return
		}
		if obj := p.Types.Scope().Lookup("Detector"); obj != nil {
			if i, ok := obj.Type().Underlying().(*types.Interface); ok {
				iface = i
			}
		}
	})
	return iface
}

func render(entries []entry) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by detectors-gen. DO NOT EDIT.\n\n")
	b.WriteString("package all\n\nimport (\n")
	b.WriteString("\t\"" + detectPath + "\"\n")
	seen := map[string]bool{}
	for _, e := range entries {
		if !seen[e.pkgPath] {
			seen[e.pkgPath] = true
			b.WriteString("\n\t\"" + e.pkgPath + "\"\n")
		}
	}
	b.WriteString(")\n\n")
	b.WriteString("// Builtin returns every built-in detector, sorted by import path then\n")
	b.WriteString("// constructor. The composition root adds them to the catalog explicitly\n")
	b.WriteString("// (no init() registration, decision D4).\n")
	b.WriteString("func Builtin() []detect.Detector {\n\treturn []detect.Detector{\n")
	for _, e := range entries {
		b.WriteString("\t\t" + e.pkgName + "." + e.fn + "(),\n")
	}
	b.WriteString("\t}\n}\n")
	return format.Source(b.Bytes())
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("detectors-gen: go.mod not found above %s", dir)
		}
		dir = parent
	}
}
