// Package watermark implements real-time cryptographic token watermarking and statistical verification
// for AI-generated text pursuant to EU AI Act Article 50 (ARCHITECTURE.md §13, §16).
package watermark

import (
	"time"
)

// WatermarkConfig specifies the parameters for the Kirchenbauer greenlist watermark algorithm.
type WatermarkConfig struct {
	SecretKey  string  `json:"secretKey"`
	Gamma      float64 `json:"gamma"`      // Fraction of vocabulary partitioned into greenlist (default 0.5)
	Delta      float64 `json:"delta"`      // Logit bias (strength)
	HashWindow int     `json:"hashWindow"` // Previous token context window (default 1)
}

// DefaultWatermarkConfig returns standard robust watermark parameters.
func DefaultWatermarkConfig(secretKey string) WatermarkConfig {
	return WatermarkConfig{
		SecretKey:  secretKey,
		Gamma:      0.5,
		Delta:      2.0,
		HashWindow: 1,
	}
}

// VerificationResult contains the statistical confidence that text was generated by a watermarked model.
type VerificationResult struct {
	TotalTokens    int       `json:"totalTokens"`
	GreenlistCount int       `json:"greenlistCount"`
	ExpectedGreen  float64   `json:"expectedGreen"`
	ZScore         float64   `json:"zScore"`        // Standard deviations above random baseline
	PValue         float64   `json:"pValue"`        // Statistical significance (p < 0.01 = 99% confidence)
	IsWatermarked  bool      `json:"isWatermarked"` // z >= 4.0
	Confidence     float64   `json:"confidence"`    // 0.0 - 1.0
	VerifiedAt     time.Time `json:"verifiedAt"`
}
